# Generated by Django 3.1.5 on 2021-01-06 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='isLiked',
        ),
    ]
